### ISSUE TITLE
[Feature]: use webhooks to verify mutually exclusive fields

### ISSUE THREAD

**Issue by whg517** [zncdatadev/operator-go#139]
### Duplicates

I have searched the existing issues

### Summary 💡

In some field attributes, it is necessary to verify the mutually exclusive condition of the attribute fields. The oneof field configuration cannot be generated using kubebuilder's mark, so it is necessary to implement the logical verification on the server side through webhook.

expect:

```yaml
spec:
  description: AuthenticationClassSpec defines the desired state of AuthenticationClass
  oneOf:
    - required:
        - static
    - required:
        - ldap
    - required:
        - oidc
    - required:
        - tls
  properties:
    provider:
      properties:
        ldap:
          type: object
        oidc:
          type: object
        static:
          type: object
        tls:
          type: object
      type: object
  type: object
```

Actual kubebuilder can only be generated:

```yaml
spec:
  description: AuthenticationClassSpec defines the desired state of AuthenticationClass
  properties:
    provider:
      properties:
        ldap:
          type: object
        oidc:
          type: object
        static:
          type: object
        tls:
          type: object
      type: object
  type: object
```
