### ISSUE TITLE
[Feature]: S3connection credential support SecretClass and SecretClass scope

### ISSUE THREAD

**Issue by whg517** [zncdatadev/operator-go#50]
### Summary 💡

Use SecretClass to provide authentication secrets for S3connection.

track list:

- [x] https://github.com/zncdatadev/operator-go/pull/53
- [x] https://github.com/zncdatadev/commons-operator/issues/38

### Examples 🌈

Current:

```yaml
apiVersion: zncdata.dev/v1alpha1
kind: S3Connection
metadata:
  name: s3connection-sample
spec:
  credential:
    existSecret: s3connection-sample-root-1

```

New

```yaml
apiVersion: zncdata.dev/v1alpha1
kind: S3Connection
metadata:
  name: s3connection-sample
spec:
  credential:
    secretClass: s3connection-sample
    scope:
      # node: true
      pod: true
      # services: 
      #   - foo
      #   - bar

```
