### ISSUE TITLE
[Feature]: Add AuthenticationClass support oidc ldap tls and static

### ISSUE THREAD

**Issue by whg517** [zncdatadev/operator-go#54]
### Duplicates

I have searched the existing issues

### Summary 💡

Use the AuthenticationClass to define a common authentication structure. Supports oidc ldap tls and static

track list:

- [ ] operator-go types defination
- [ ] https://github.com/zncdatadev/commons-operator/issues/39

### Examples 🌈

example: 

**ldap**

```yaml
apiVersion: authentication.zncdata.dev/v1alpha1
kind: AuthenticationClass
metadata:
  name: trino-auth
spec:
  ldap:
    hostname: ldap.example.com
    port: 389
    ldapFieldNames:
      email: mail
      GivenName: givenName
      Surname: sn
      username: uid
      uid: uid
    searchBase: ou=people,dc=example,dc=com
    searchFilter: (uid={0})
    credentials:
      secretClass: ldap-secret
      scopes:
        node: true
        pod: true
        services:
          - foo
          - bar
      
```

**oidc**

```yaml
apiVersion: authentication.zncdata.dev/v1alpha1
kind: AuthenticationClass
metadata:
  name: trino-auth
spec:
  oidc:
    hostname: https://example.com
    port: 443
    principalClaim: preferred_username
    providerHint: keycloak
    rootPath: /auth/realms/master
    Scopes:
      - openid
      - email
      - profile
    tls:
      secretClass: my-tls-secret
      Scopes:
        node: true
        pod: true
        services:
          - foo
          - bar

```

**TLS**

```yaml
apiVersion: authentication.zncdata.dev/v1alpha1
kind: AuthenticationClass
metadata:
  name: trino-auth
spec:
  tls:
    secretClass: my-secret-class

```

**static**

```yaml
apiVersion: authentication.zncdata.dev/v1alpha1
kind: AuthenticationClass
metadata:
  name: trino-auth
spec:
  provider:
    static:
      cerdentialSecret: database-sample-credentials
```
